### PR TITLE
Fixed excessive IndexOutOfBoundsExceptions

### PR DESCRIPTION
**Pull request by avandeweghe**

### CODE REVIEW

**Comment by zecjy** [comment]
I can confirm this as working!
Was about to create a pull request too :D

**Comment by Dragonflyss** [comment]
So what should we do? Please explain

**Comment by rawr1** [comment]
@Dragonflyss you can clone the repo and edit this file manually before compiling. Or wait for Ember to merge the pull request.

Does this change affect the crashes when the game ends?

**Comment by Ajbolitt76** [comment]
@avandeweghe Are you sure that removing this throw won't cause random radar crashes? This exception may have purpose. Also this commit won't fix main problem - memory leak.

**Comment by schulzjona** [comment]
@Ajbolitt76 is right, this wn't fix the problem, the problem just won't be printed anymore. Maybe I will try something later with that

**Comment by schulzjona** [comment]
it "fixes" nothing. It just disables the possibilty that the error is shown up correctly

**Comment by L-KE** [comment]
@avandeweghe No it doesn't, it just stops it throwing the error, which is not the same as fixing the problem. A real fix would be to allow the program to recover from the problem instead of just throwing an error repeatedly.

**Comment by L-KE** [comment]
@avandeweghe why the new commits?

**Pull request closed without merging**
